# Fastfile 
# Copyright@2017 Abyss

fastlane_version "2.69.2"
default_platform :ios

platform :ios do

	before_all do
	end

	import_from_git(
		url: 'https://github.com/RogerAbyss/AFastlane.git', 
		branch: '0.0.6',
		path: 'fastlane/IOSAppFastfile'
	  )

	# 本地调试
	# import("/Users/abyss/Documents/Projects/Abyss/fastlane/fastlane/IOSAppFastfile")
	  
	after_all do
	end
end