# https://docs.travis-ci.com/

language: minimal

services:
  - docker

addons:
  hosts:
    - server.localhost
    - www-server.localhost
    - www.server.localhost
    - secure.server.localhost
    - www.secure.server.localhost
  apt:
    packages:
      - docker-ce

install:
  - curl -sSL https://github.com/h5bp/server-configs-test/releases/download/1.0.6/server-configs-test.tar.gz | tar -xz -C test/

before_script:
  - docker pull nginx
  - |
    docker run -d -p 80:80 -p 443:443 --name server \
      -v $TRAVIS_BUILD_DIR/test/fixtures:/var/www/server.localhost \
      -v $TRAVIS_BUILD_DIR/test/vhosts:/etc/nginx/conf.d \
      -v $TRAVIS_BUILD_DIR/test/certs:/etc/nginx/certs \
      -v $TRAVIS_BUILD_DIR/h5bp:/etc/nginx/h5bp \
      -v $TRAVIS_BUILD_DIR/nginx.conf:/etc/nginx/nginx.conf \
      -v $TRAVIS_BUILD_DIR/mime.types:/etc/nginx/mime.types \
      nginx

script:
  - ./test/bin/k6 run test/lib/index.js -e TESTS=basic-file-access:cache-busting:custom-errors:forbidden-files:precompressed-files-gzip:rewrites:ssl

after_success: ./test/bin/k6 run test/lib/benchmark.js

after_failure:
  - docker ps -a
  - docker logs server
