source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/rogerabyss/myrepo.git'

platform :ios, '9.0'
use_frameworks!

target 'VirtualCoins' do
    # ==== must use Pod ====
    # Fabric & Crashlytics
    # https://get.fabric.io/
    pod 'Fabric'
    pod 'Crashlytics'
    # Moya
    # https://github.com/Moya/Moya
    pod 'Moya', '~> 11.0.2'
    # R
    # https://github.com/mac-cain13/R.swift
    pod 'R.swift'
    # 上下拉
    # https://github.com/CoderMJLee/MJRefresh
    pod 'MJRefresh'
    # skeleton UI
    pod "SkeletonView", "~> 1.2"

    ######################
    # optional
    ######################
    
    # UPush
    # pod 'UMCCommon'
    # pod 'UMCPush'
    # pod 'UMCSecurityPlugins'

    # 二维码扫描和生成
    # pod 'swiftScan', '~> 1.1.2'

    # seg
    # pod 'Segmentio', '~> 3.0'
    
    # photoPicker
    # pod 'YPImagePicker'

    # banner
    # pod 'FSPagerView'

    # 密码框
    # pod 'SVPinView'

    # 弹出菜单
    # pod 'NewPopMenu'

    # K-line股市
    # pod 'CHKLineChartKit'
end
