---

abyss_public: 
  # 个人文档-GitBook
  - git@github.com:RogerAbyss/AGitBook.git
  # Mac一键重装-MacSystemDotfile
  - git@github.com:RogerAbyss/ADotfile.git
  # 个人主页-Github Pages
  - git@github.com:RogerAbyss/RogerAbyss.github.io.git
  # Docker
  - git@github.com:RogerAbyss/ADocker.git
  # App 原生自动构建
  - git@github.com:RogerAbyss/AFastlane.git

private:
  # Pod私有仓库
  - git@gitee.com:rogerabyss/myrepo.git
  # 华硕B85Pro+GTX960+V31230 黑苹果EFI
  - git@github.com:RogerAbyss/AHacktoish.git
  # zgxl证书仓库
  - git@gitee.com:rogerabyss/PPMatchRelease.git
  # 个人服务器 - node
  - git@gitee.com:rogerabyss/abyss-node.git
  # 资源仓库 - Asserts
  - git@gitee.com:rogerabyss/Assert.git
  # 微信小程序 - Lrene
  - git@gitee.com:rogerabyss/wx.git

# 常用静态库
framework:
  - git@github.com:RogerAbyss/AUpdater.git
  - git@github.com:RogerAbyss/ARouter.git

opensource:
  # git忽略
  - git@github.com:github/gitignore.git

# zsh相关
zsh:
  - git@github.com:agnoster/agnoster-zsh-theme.git
  - git@github.com:powerline/fonts.git
  - git@github.com:altercation/solarized.git


# 以下为私人fork项目, 防止一天停止维护
# fork:
#   - git@github.com:RogerAbyssWorld/JrebelBrainsLicenseServerforJava.git
#   - git@github.com:RogerAbyssWorld/WeChatPlugin-MacOS.git
#   - git@github.com:RogerAbyssWorld/QQPlugin-macOS.git
#   - git@github.com:RogerAbyssWorld/WeChatPlugin-iOS.git
#   - git@github.com:RogerAbyssWorld/slshim.git
##  私人框架(Objective-C)
#   - git@gitee.com:rogerabyss/AFramework.git
#   - git@gitee.com:rogerabyss/AModule.git
#   - git@gitee.com:rogerabyss/ALauncher.git
#   - git@gitee.com:rogerabyss/AExtension.git
#   - git@gitee.com:rogerabyss/ANetWork.git
#   - git@gitee.com:rogerabyss/ADebug.git